### ISSUE TITLE
Upload code

### ISSUE THREAD

**Issue by solleer** [Level-2/Router#1]

**Comment by solleer** [comment]
I would really appreciate it if you could upload the Router code. I am waiting on it before I start working on some projects. Thank you.

**Comment by TRPB** [comment]
I was planning to add more documentation to this before uploading. For now it's uploaded as-is.

This is just a skeleton router that needs extending with rules (I may rename these to modules as it will make more sense!). See https://github.com/Level-2/Router-ModuleJson (going up shortly) for an example that uses a JSON format, along with Level-2/Dice to build the object.

**Comment by solleer** [comment]
Thank you so much!!!
